version: '2'

services:
  draw-image-export:
    image: hub.qucheng.com/app/draw-image-export:${TAG:-latest}
    container_name: draw-image-export
    ports:
      - '8000:8000'
    environment:
      - DRAWIO_SERVER_URL=http://localhost:8080
      - DEBUG=1
      - IS_CONTAINER=true
    networks:
      - net

networks:
  net:
    driver: bridge

